services:
  back-end:
    command: npm run dev
    volumes:
      - ./backend:/usr/src/app/backend
      - ~/docker-secrets/solana-keypair:/usr/src/app/backend/secrets/solana-keypair.json:ro

  front-end:
    command: npm run dev
    volumes:
      - ./frontend:/usr/src/app/frontend
