[toolchain]

[features]
resolution = true
skip-lint = false

[programs.mainnet]
jailbreak_pool = "43m2CSa83AVK6yT7SpZ1KFcScWfxyfid7nQx2KUMWJko"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Mainnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
